/* 1: Get names of all customers who had made a booking for an suv type car */
Select Name,type from 
Booking_Details
INNER JOIN Vehicle_Type
ON Booking_Details.Vehicle_ID=Vehicle_Type.Vehicle_ID
inner join Customer_Details on Customer_Details.Customer_ID=Booking_Details.Customer_ID
Where Vehicle_Type.Type='SUV';

SELECT Name,PhNo,Email from Customer_Details Where Customer_Details.Customer_ID in
(
       SELECT Customer_ID from Booking_Details where Booking_details.Vehicle_ID in
        (
            Select Vehicle_ID from Vehicle_details where Vehicle_details.VehicleType_ID in
            (
                Select VehicleType_ID from Vehicle_Type where Type='SUV' 
            )
        ) 
);

Select Name,PhNo,Email FROM
Customer_Details
inner join (Booking_Details inner join (Vehicle_Details inner join vehicle_type on Vehicle_Details.VehicleType_ID = Vehicle_Type.VehicleType_ID)
on Booking_Details.Vehicle_ID=Vehicle_details.Vehicle_ID)
on Customer_Details.Customer_ID=Booking_Details.Booking_ID
Where vehicle_type.type='SUV';


/* 
2: Get number of bills generated by the admin suhas */
SELECT COUNT(*) Name 
FROM Bill 
LEFT OUTER JOIN Admin
ON Bill.Admin_ID = Admin.Admin_ID 
WHERE Name='Suhas';

/* 3: Get sum of all amounts for bookings made between 10th of may and 13th of may 2020*/
SELECT SUM(Amount) Amount FROM Booking_Details WHERE Date BETWEEN '2020-05-10' AND '2020-05-13';

/* 4: Return the number of vehicles currently available*/
SELECT COUNT(*) Vehicle_ID FROM Vehicle_Details WHERE Availability='Y';

/* 5: Return all drivers who have a rating of 8.5 and above*/
SELECT Name,Email,PhNo,Rating FROM Driver_Details WHERE RATING >= 8.5;

With tmp as(select VehicleType_ID,Counut(*) as count_times from
Booking_Details
inner join Vehicle_Details
on Booking_Details.Vehicle_ID=Vehicle_Details.Vehicle_ID
group by VehicleType_ID) select Type from vehicle_type where VehicleType_ID in (select VehicleType_ID from
tmp where count_times =(select max(count_times) from tmp));