/* 1: Get names of all customers who had made a booking for an suv type car */
SELECT Name,PhNo,Email FROM Customer_Details WHERE Customer_Details.Customer_ID IN(
       SELECT Customer_ID FROM Booking_Details WHERE Booking_details.Vehicle_ID IN(
            SELECT Vehicle_ID FROM Vehicle_details WHERE Vehicle_details.VehicleType_ID IN(
               SELECT VehicleType_ID FROM Vehicle_Type WHERE Type='SUV' )));

/* 2: Get number of bills generated by the admin suhas */
SELECT COUNT(*) Name 
FROM Bill 
LEFT OUTER JOIN Admin
ON Bill.Admin_ID = Admin.Admin_ID 
WHERE Name='Suhas';

/* 3: Get sum of all amounts for bookings made between 10th of may and 13th of may 2020*/
SELECT SUM(Amount) Amount FROM Booking_Details WHERE Date BETWEEN '2020-05-10' AND '2020-05-13';

/* 4: Return the number of vehicles currently available*/
SELECT COUNT(*) Vehicle_ID FROM Vehicle_Details WHERE Availability='Y';

/* 5: Return all drivers who have a rating of 8.5 and above*/
SELECT Name,Email,PhNo,Rating FROM Driver_Details WHERE RATING >= 8.5;

/* 6: Return the type of car which is booked the maximum number of times*/
WITH Temp AS(
SELECT VehicleType_ID,COUNT(*) AS Count_Times 
FROM Booking_Details
INNER JOIN Vehicle_Details
ON Booking_Details.Vehicle_ID=Vehicle_Details.Vehicle_ID
GROUP BY VehicleType_ID) 
SELECT Type FROM Vehicle_Type WHERE VehicleType_ID IN(
SELECT VehicleType_ID 
FROM Temp 
WHERE Count_Times =(SELECT MAX(Count_Times) FROM Temp));